---
- stat: path=/tmp/openresty.tar.gz
  register: resty_tar

- stat: path=/usr/sbin/nginx
  register: resty_exe

- name: Check if openresty already installed
  shell: nginx -v
  register: nginx_ver

- name: Update apt
  apt: update_cache=yes
  when: nginx_ver.stderr.find(openresty_version) == -1

- name: Install required packages to compile Openresty from source
  apt: name={{ item }}
  with_items:
    - nginx-extras
    - build-essential
    - libreadline-dev
    - make
    - libncurses5-dev
    - libpcre3-dev
    - libssl-dev
    - perl
    - libxml2-dev     #Optional
    - libxslt-dev     #Optional
    - libgd-dev       #Optional
    - libgeoip-dev    #Optional
    - libpq-dev       #Optional
    - libgd2-xpm-dev  #Optional
    - libxslt1-dev    #Optional
  when: nginx_ver.stderr.find(openresty_version) == -1

- name: Download Openresty source
  get_url: url={{ openresty_download_url }}{{ openresty_version }}.tar.gz dest=/tmp/openresty.tar.gz mode=0440 validate_certs=no
  when: resty_tar.stat.exists == False or nginx_ver.stderr.find(openresty_version) == -1

- name: Extract Openresty tarball
  unarchive: src=/tmp/openresty.tar.gz dest=/tmp/ copy=no
  when: resty_tar.stat.exists == False or nginx_ver.stderr.find(openresty_version) == -1

- name: Build configure command
  template: src=configure_command.j2 dest=/tmp/openresty-{{ openresty_version }}/ansible_build.sh mode=0777
  when: nginx_ver.stderr.find(openresty_version) == -1

- name: Configure Openresty
  command: chdir=/tmp/openresty-{{ openresty_version }} ./ansible_build.sh
  when: nginx_ver.stderr.find(openresty_version) == -1

- name: Compile Openresty
  command: chdir=/tmp/openresty-{{ openresty_version }} make
  when: nginx_ver.stderr.find(openresty_version) == -1

- name: Install Openresty
  command: chdir=/tmp/openresty-{{ openresty_version }} make install
  when: nginx_ver.stderr.find(openresty_version) == -1

- name: Service command
  template: src=service.j2 dest=/etc/init.d/nginx owner=root group=root mode=0777
  when: nginx_ver.stderr.find(openresty_version) == -1
